server_primary:
  enable: true
  type: PRIMARY
  mqtt_versions: MQTT_5_0
  port: 8883
  worker: 8
  host: "0.0.0.0"
  tls:
    enable: true
    type: SERVER_TLS
    tls_cert_file: "/etc/ssl/cert.pem"
    tls_key_file: "/etc/ssl/key.pem"

server_secondary:
  enable: true
  type: SECONDARY
  port: 8884
  tls:
    enable: false
    type: NONE

auth_config:
  enable: true
  auth_client_id: true
  auth_username_password: false

vmbox:
  ipc_type: VMBOX_UNIX_SOCKET
  ipc_connection_type: VMBOX_ROUTER
  port: 1885
  worker: 6
  mailbox_connect_timeout: 10
  mailbox_query_timeout: 5
  enable_backpressure_control: true
  ingress_backlog_number: 50
  ingress_backlog_cooldown: 200
  egress_backlog_number: 40
  egress_backlog_cooldown: 300
  max_mailbox: 1000
  host: "localhost"

payload_limit:
  max_publish_bytes: 4194304
  ipc_chunk_bytes: 65536

topics:
  - topic_id: "/sensor/data"
    max_client: 100
    pacing: 100
    enable: true

topic_limiters:
  - topic_filter: "/sensor/#"
    pub_pacing: 50
    sub_pacing: 60

storm_guard:
  enable: true
  modules:
    - module_id: "guard1"
      enable: true
      properties:
        limit: "50"
        ttl: "30"
